// pages/components/topbar.tsx
import Image from "next/image";
import Link from "next/link";

import webring from "../../public/icons/webring.svg";
import creatorsgarten from "../../public/icons/ring-thin.svg";
import logo from "../../public/tinarskii.png";

export default function Topbar() {
  return (
    <>
      {/* Top bar elements */}
      <div className="flex w-full flex-row items-center justify-between gap-12">
        {/* Rings */}
        <div className="top-0 left-0 mx-0 flex flex-row items-center gap-4">
          <Link href="https://creatorsgarten.org/ring" className="max-w-[32px]">
            <Image
              src={creatorsgarten}
              alt="Creatorsgarten Ring"
              className="h-[32px] w-[32px]"
            />
          </Link>
          <Link
            href="https://webring.wonderful.software#tinarskii.com"
            className="max-w-[32px]"
          >
            <Image
              src={webring}
              alt="Webring.in.th Ring"
              className="h-[32px] w-[32px]"
            />
          </Link>
        </div>

        {/* Logo */}
        <div className="block">
          <Link href="/">
            <Image
              src={logo}
              alt="Tinarskii"
              className="ml-auto h-[44px] w-[320px] cursor-pointer invert"
            />
          </Link>
        </div>
      </div>
    </>
  );
}

// components/TopBar.vue
<template>
  <!-- Top bar elements -->
  <div class="flex w-full flex-row items-center justify-between gap-12">
    <!-- Rings -->
    <div class="top-0 left-0 mx-0 flex flex-row items-center gap-4">
      <NuxtLink
        to="https://creatorsgarten.org/ring"
        title="Creatorsgarten Ring"
        class="max-w-[32px]"
      >
        <img
          src="/icons/ring-thin.svg"
          alt="Creatorsgarten Ring"
          class="sm:w-[32px] sm:h-[32px] w-[16px] h-[16px]"
        />
      </NuxtLink>
      <NuxtLink
        to="https://webring.wonderful.software#tinarskii.com"
        title="วงแหวนเว็บ"
        class="max-w-[32px]"
      >
        <img
          src="/icons/webring.svg"
          alt="Webring.in.th Ring"
          class="sm:w-[32px] sm:h-[32px] w-[16px] h-[16px]"
        />
      </NuxtLink>
    </div>

    <!-- Logo -->
    <div class="block">
      <NuxtLink to="/">
        <!-- 8.3 : 1 (Shitty ratio i know) -->
        <img
          src="/wordmark.png"
          alt="TINARSKII"
          class="sm:w-[300px] w-[256px] ml-auto cursor-pointer"
        />
      </NuxtLink>
    </div>
  </div>
</template>
